version: '3.7'
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    # volumes:
    #   - ./docker/mariadb/data:/var/lib/mysql
    # environment:
    #   MYSQL_ROOT_PASSWORD: 123456

  php-fpm:
    build: ./docker/php-fpm
    image: xxt/php-fpm
    # restart: always
    volumes:
      - .:/usr/share/nginx/html

  nginx:
    build: ./docker/nginx
    image: xxt/nginx
    restart: always
    volumes:
      - .:/usr/share/nginx/html
    links:
      - php-fpm
    # ports:
    #   - 8080:80
    # environment:
    #   - NGINX_HTTP_PROTOCOL=http
    #   - NGINX_HTTP_HOST=localhost
    #   - NGINX_HTTP_PORT=8080

  adminer:
    image: adminer
    restart: always
    # ports:
    #   - 9090:8080

  mongodb:
    image: mongo:latest
    restart: always
    # ports:
    #   - '27017:27017'
    # volumes:
    #   - ./docker/mongodb/data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    logging:
      driver: 'none'

  api:
    build: ./api
    image: xxt/api:latest
    # ports:
    # - 3000:3000
